import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster";
import { getUser } from "@/app/auth";
import { SignInButton } from "@/components/signInButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, user } = await getUser();

  if (!isAuthenticated || !user) {
    return (
      <html lang="en">
        <body
          className={`${inter.className} flex items-center justify-center bg-zinc-800`}
        >
          <main>
            <SignInButton />
          </main>
        </body>
      </html>
    );
  }


  return (
    <html lang="en">
      <body
        className={`${inter.className} flex items-start justify-between bg-zinc-800`}
      >
        <Sidebar user={user} />
        <main className="grid h-full w-full pl-[300px]">
          <Header />
          <div className="p-8">{children}</div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
